# Generated by Django 5.0.6 on 2024-06-29 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_classtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='classtest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.classtest'),
        ),
        migrations.AddField(
            model_name='post',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
